sequenceDiagram
    participant browser
    participant server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: [{ "content": "Single page app Diagram", "date": "2023-1-1" }, ... ]
    deactivate server
    